#!/bin/bash
# codex.sh — Adapter: Core → AGENTS.md + GEMINI.md mirrors
#
# AGENTS.md serves Codex and Visual Studio-family agent surfaces.
# GEMINI.md serves Gemini CLI, Gemini Code Assist, and Antigravity-family agents.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
source "$SCRIPT_DIR/acl.sh"

VERSION=$(acl_version)
SKILLS_COUNT=$(acl_count_skills)
AGENTS_COUNT=$(acl_count_agents)
COMMANDS_COUNT=$(acl_count_commands)
PROMPTS_COUNT=$(acl_count_prompts)
CONSTITUTION=$(acl_constitution_version)

echo "Adapter: Core → AGENTS + GEMINI mirrors"

# ── AGENTS.md (OpenAI Codex + Visual Studio-family agents) ──

cat > "$PROJECT_ROOT/AGENTS.md" << AGENTS
# JM-ADK v$VERSION — AGENTS Runtime Instructions

<!-- Generated by scripts/adapters/codex.sh. Do not edit manually; update the adapter or canonical contracts. -->

## Runtime Targets

Primary: OpenAI Codex and Visual Studio-family agent surfaces.
Role: homologated AGENTS mirror for runtimes that load \`AGENTS.md\`.

## Environment

IDE family: agents | Triad: sequential/checklist by runtime | Tools: MCP via config (see Tool Access) | MCP: yes via \`~/.codex/config.toml\` | Multimodal: runtime-dependent
Components: $SKILLS_COUNT skills · $AGENTS_COUNT agents · $COMMANDS_COUNT commands · $PROMPTS_COUNT prompts

## Awakening

Read: PRISTINO.md → Constitution $CONSTITUTION → PRISTINO-INDEX.md → diagnose first-use → diagnose user-context → greet

## First Use

- Greeting-only or empty input: run guided setup before technical work.
- Explicit task: collect only missing critical context, then proceed.
- Repo not confirmed as Alfa: report \`Dato requerido\` and do not edit.
- Diagnosis command: \`python3 scripts/diagnose-first-use.py --dry-run\`.

## Runtime Context Contract

$(acl_runtime_context_contract)

## Input Tolerance

$(acl_input_tolerance)

## Auto-Prompt Matching

Auto-select the best skill for intent. Confidence ≥ 0.85 → execute. 0.60-0.84 → offer options. < 0.60 → ask.

## Triad Pattern

$(acl_sequential_triad)

## Request Classification

$(acl_request_classification)

## Core Rules

$(acl_core_rules | head -6 | sed 's/^/- /')

## Quality Gates

$(acl_quality_gates)

## Tool Access (MCP)

$(acl_tool_access_contract)
- Codex CLI wiring: define \`[mcp_servers.workspace-mcp]\` in \`~/.codex/config.toml\` (or project \`.codex/config.toml\`), or run \`codex mcp add workspace-mcp -- uvx workspace-mcp\`. Template: \`references/mcp/codex.config.toml.example\`.

## Placement & Naming Contract

- Task deliverables → \`workspace/{active}/artifacts/\`. Task scaffolding stays at task root. Never mix system files with deliverables.
- Durable context → \`user-context/\` only after explicit context-update instruction; context repo identity marker: \`user-context/.jm-adk-context.json\`.
- Kit internals (skills/agents/scripts/references) → maintainer mode only.
- Filenames + slugs = kebab-case \`^[a-z0-9]+(-[a-z0-9]+)*\$\`, concise, mnemonic, no spaces/accents/CamelCase.
- If hooks are unavailable, apply this contract manually. Full contract: \`references/ontology/placement-naming-contract.md\`.

## References

Soul: PRISTINO.md | Index: PRISTINO-INDEX.md | Constitution: references/ontology/constitution-$CONSTITUTION.md

## Requires

- **Primary**: OpenAI Codex; Visual Studio-family agent surfaces that honor AGENTS.md.
- **Runtime-dependent**: hooks, MCP, workspace automation, multimodal input, and subagents.
AGENTS

echo "  Generated: AGENTS.md"

# ── GEMINI.md (Gemini CLI + Gemini Code Assist + Antigravity family) ──

cat > "$PROJECT_ROOT/GEMINI.md" << GEMINI
# JM-ADK v$VERSION — GEMINI Runtime Instructions

<!-- Generated by scripts/adapters/codex.sh. Do not edit manually; update the adapter or canonical contracts. -->

## Runtime Targets

Primary: Gemini CLI, Gemini Code Assist, and Antigravity-family Gemini agents.
Role: homologated GEMINI mirror for runtimes that load \`GEMINI.md\` or a Gemini adapter bridge.

## Environment

IDE family: gemini | Triad: sequential/adapter-guided by runtime | Tools: MCP via config (see Tool Access) | Hooks: runtime-dependent | MCP: yes via \`~/.gemini/settings.json\` | Multimodal: runtime-dependent
Components: $SKILLS_COUNT skills · $AGENTS_COUNT agents · $COMMANDS_COUNT commands · $PROMPTS_COUNT prompts

## Awakening

Load: PRISTINO.md → Constitution $CONSTITUTION → PRISTINO-INDEX.md → diagnose first-use → diagnose user-context → greet.

## First Use

- Greeting-only or empty input: run guided setup before technical work.
- Explicit task: collect only missing critical context, then proceed.
- Repo not confirmed as Alfa: report \`Dato requerido\` and do not edit.
- Diagnosis command: \`python3 scripts/diagnose-first-use.py --dry-run\`.

## Runtime Context Contract

$(acl_runtime_context_contract)

## Input Tolerance

$(acl_input_tolerance)

## Auto-Prompt Matching

Auto-select the best skill for intent. Confidence ≥ 0.85 → execute. 0.60-0.84 → offer options. < 0.60 → ask.

## Triad Pattern

$(acl_sequential_triad)

## Request Classification

$(acl_request_classification)

## Core Rules

$(acl_core_rules | head -6 | sed 's/^/- /')

## Quality Gates

$(acl_quality_gates)

## Tool Access (MCP)

$(acl_tool_access_contract)
- Gemini CLI wiring: add \`workspace-mcp\` under \`mcpServers\` in \`~/.gemini/settings.json\` (or project \`.gemini/settings.json\`); optionally gate with \`mcp.allowed\`. Template: \`references/mcp/gemini.settings.json.example\`.

## Placement & Naming Contract

- Task deliverables → \`workspace/{active}/artifacts/\`. Task scaffolding stays at task root. Never mix system files with deliverables.
- Durable context → \`user-context/\` only after explicit context-update instruction; context repo identity marker: \`user-context/.jm-adk-context.json\`.
- Kit internals (skills/agents/scripts/references) → maintainer mode only.
- Filenames + slugs = kebab-case \`^[a-z0-9]+(-[a-z0-9]+)*\$\`, concise, mnemonic, no spaces/accents/CamelCase.
- If hooks are unavailable, apply this contract manually. Full contract: \`references/ontology/placement-naming-contract.md\`.

## References

- Soul: \`PRISTINO.md\` | Constitution: \`references/ontology/constitution-$CONSTITUTION.md\`
- Index: \`PRISTINO-INDEX.md\` | Brand: \`references/brand/design-tokens.json\`

## Requires

- **Primary**: Gemini CLI, Gemini Code Assist, Antigravity-family Gemini agents.
- **Bridge**: Antigravity may load \`.agent/rules/GEMINI.md\`, generated as a GEMINI mirror.
- **Runtime-dependent**: hooks, MCP, workspace automation, multimodal input, and subagents.
GEMINI

echo "  Generated: GEMINI.md"
echo "ADAPTER-COMPLETE: agents+gemini"
