#!/usr/bin/env bash
# Generate PRISTINO-INDEX.md from component frontmatter
# Usage: bash scripts/generate-pristino-index.sh

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

OUT="PRISTINO-INDEX.md"

echo "# Pristino Master Index" > "$OUT"
echo "" >> "$OUT"
echo "<!-- Auto-generated by scripts/generate-pristino-index.sh. Do not edit manually. -->" >> "$OUT"

AGENT_COUNT=$(find agents -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')
SKILL_COUNT=$(find skills -mindepth 2 -maxdepth 2 -name 'SKILL.md' -type f | wc -l | tr -d ' ')
CMD_COUNT=$(find commands -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')
PROMPT_COUNT=$(find prompts -mindepth 2 -maxdepth 2 -name '*.md' -not -path '*/.catalog/*' | wc -l | tr -d ' ')
TOTAL_COUNT=$((AGENT_COUNT + SKILL_COUNT + CMD_COUNT + PROMPT_COUNT))

echo "<!-- Counts: ${SKILL_COUNT} Skills | ${AGENT_COUNT} Agents | ${CMD_COUNT} Commands | ${PROMPT_COUNT} Prompts | ${TOTAL_COUNT} Components -->" >> "$OUT"
echo "" >> "$OUT"

# Agents
echo "## Agents (${AGENT_COUNT})" >> "$OUT"
echo "" >> "$OUT"
echo "| # | ID | Description |" >> "$OUT"
echo "|---|-----|-------------|" >> "$OUT"
i=1
for f in agents/*.md; do
  name=$(grep '^name:' "$f" | head -1 | sed 's/name: *//;s/"//g')
  desc=$(grep '^description:' "$f" | head -1 | sed 's/description: *//;s/"//g' | cut -c1-80)
  echo "| $i | \`$name\` | $desc |" >> "$OUT"
  i=$((i+1))
done

# Skills
echo "" >> "$OUT"
echo "## Skills (${SKILL_COUNT})" >> "$OUT"
echo "" >> "$OUT"
echo "| # | ID | Description |" >> "$OUT"
echo "|---|-----|-------------|" >> "$OUT"
i=1
for f in skills/*/SKILL.md; do
  name=$(grep '^name:' "$f" | head -1 | sed 's/name: *//;s/"//g')
  desc=$(grep '^description:' "$f" | head -1 | sed 's/description: *//;s/"//g;s/> *//')
  [ -z "$desc" ] && desc="—"
  echo "| $i | \`$name\` | ${desc:0:80} |" >> "$OUT"
  i=$((i+1))
done

# Commands
echo "" >> "$OUT"
echo "## Commands (${CMD_COUNT})" >> "$OUT"
echo "" >> "$OUT"
echo "| # | ID | Description |" >> "$OUT"
echo "|---|-----|-------------|" >> "$OUT"
i=1
for f in commands/*.md; do
  id=$(basename "$f" .md)
  desc=$(grep '^description:' "$f" | head -1 | sed 's/description: *//;s/"//g' | cut -c1-80)
  echo "| $i | \`$id\` | $desc |" >> "$OUT"
  i=$((i+1))
done

# Prompts
echo "" >> "$OUT"
echo "## Prompts (${PROMPT_COUNT})" >> "$OUT"
echo "" >> "$OUT"
echo "| # | ID | Category |" >> "$OUT"
echo "|---|-----|----------|" >> "$OUT"
i=1
for f in $(find prompts -name '*.md' -not -path '*/.catalog/*' | sort); do
  id=$(basename "$f" .md)
  cat=$(echo "$f" | sed 's|prompts/||;s|/.*||')
  echo "| $i | \`$id\` | $cat |" >> "$OUT"
  i=$((i+1))
done

echo ""
echo "Generated: $OUT"
echo "Agents: $AGENT_COUNT | Skills: $SKILL_COUNT | Commands: $CMD_COUNT | Prompts: $PROMPT_COUNT | Components: $TOTAL_COUNT"
